GET http://localhost:44595/odata/v4/mail-reader/Attachments

###
DELETE http://localhost:4004/odata/v4/mail-reader/SelectedMail('abc@gmail.com')
###
POST  http://localhost:4004/odata/v4/mail-reader/cleardb
Content-Type: application/json


###
POST http://localhost:4004/odata/v4/mail-reader/signup
content-Type :application/json

{
       "userName"           : "user",
        "emailId"            : "user@gmail.com",
        "password"           : "user@12345",
        "isAdmin"            : true
}
###
POST http://localhost:4004/odata/v4/mail-reader/login
content-Type :application/json

{
        "emailId"            : "user@gmail.com",
        "password"           : "user@12345"
}
####
POST http://localhost:4004/odata/v4/mail-reader/SelectedMail
Content-Type: application/json

{
  
 "useremail":"btptesting7@gmail.com",
    "password":"fibq jben frcm uusi",
    "host":"imap.gmail.com",
    "port":993,
    "tls": true,
    "keywords":["invoice"],
    "markRead":true
}


###
POST http://localhost:4004/odata/v4/mail-reader/EmailConfiguration
Content-Type: application/json

{
  "fullName": "Usha Rani ",
  "emailId": "imdoddaushara@gmail.com",
  "password": "pykv zugu cigg jlaw",
  "port": 993,
  "hostName": "imap.gmail.com",
  "connectionSecurity": "SSL",
  "pollingFrequency": 15,
  "keywords": ["invoice", "Bill"],
  "markRead": false
}


###
Get https://mysubaccount-axm16i2j.it-cpitrial05-rt.cfapps.us10-001.hana.ondemand.com/http/OCR

####
POST http://localhost:34167/odata/v4/mail-reader/SelectedMail
Content-Type: application/json

{
  
 "useremail":"btptesting7@gmail.com",
    "password":"fibq jben frcm uusi",
    "host":"imap.gmail.com",
    "port":993,
    "tls": true,
    "keywords":["invoice"],
    "markRead":true
}

###
DELETE http://localhost:4004/odata/v4/mail-reader/SelectedMail('btptesting7@gmail.com')


###

GET http://localhost:4004/odata/v4/mail-reader/EmailData


### 
GET http://localhost:44595/odata/v4/mail-reader/Test(8a8b3b83-a238-4053-9b54-9de173912491)



###
